local M = {}

function M.highlight(palette, opts)
	return {
		Bold = { bold = true },
		Boolean = { fg = palette.turquoise },
		Character = { fg = palette.green },
		ColorColumn = { bg = palette.bg_1 },
		Comment = vim.tbl_extend("force", {
			fg = palette.fg_2,
			italic = true,
		}, opts.styles.comments),
		Conceal = { fg = palette.bg_2 },
		Conditional = { fg = palette.indigo },
		Constant = { fg = palette.fg_0 },
		Cursor = { fg = palette.fg_1, bg = palette.bg_0 },
		CursorColumn = { bg = palette.bg_2 },
		CursorIM = { fg = palette.fg_1, bg = palette.bg_0 },
		CursorLine = { bg = palette.bg_2 },
		CursorLineNr = { fg = palette.fg_0, bold = true },
		Debug = { fg = palette.blue },
		Define = { fg = palette.blue },
		Delimiter = { fg = palette.indigo },
		DiagnosticFloatingError = { fg = palette.error },
		Directory = { fg = palette.blue },
		EndOfBuffer = { fg = palette.bg_0 },
		Error = { fg = palette.error, bold = true },
		ErrorMsg = { fg = palette.error, bold = true },
		Exception = { fg = palette.blue },
		Float = { fg = palette.gold },
		FloatBoder = { fg = palette.fg_2, bg = palette.bg_2 },
		FloatBorder = { fg = palette.fg_1 },
		FoldColumn = { fg = palette.fg_1, bg = palette.bg_2 },
		Folded = { fg = palette.fg_1, bg = palette.bg_2 },
		Function = vim.tbl_extend("force", { fg = palette.fg_0 }, opts.styles.functions),
		Identifier = { fg = palette.fg_0 },
		Ignore = { fg = palette.fg_0, bg = palette.bg_0, bold = true },
		IncSearch = { fg = palette.bg_0, bg = palette.lemongrass }, -- fg should surely be p.bg?
		Include = { fg = palette.fg_1 },
		Italic = { italic = true },
		Keyword = vim.tbl_extend("force", { fg = palette.indigo }, opts.styles.keywords),
		Label = { fg = palette.fg_0 },
		LineNr = { fg = palette.fg_2 },
		Macro = { fg = palette.fg_0 },
		MatchParen = { fg = palette.fg_1, bg = palette.none },
		MatchParenCur = { underline = true },
		MatchWord = { underline = true },
		MatchWordCur = { underline = true },
		ModeMsg = { fg = palette.fg_0, bg = palette.bg_0 },
		MoreMsg = { fg = palette.fg_0 },
		MsgArea = { fg = palette.fg_0, bg = palette.bg_0 },
		MsgSeparator = { fg = palette.fg_0, bg = palette.bg_0 },
		NonText = { fg = palette.fg_2 },
		Normal = { fg = palette.fg_0, bg = opts.transparent and palette.none or palette.bg_0 },
		NormalFloat = { bg = palette.bg_1 },
		NormalNC = { fg = palette.fg_0, bg = palette.bg_0 },
		Number = { fg = palette.gold },
		Operator = { fg = palette.red },
		Pmenu = { fg = palette.fg_1, bg = palette.bg_1 },
		PmenuSbar = { fg = palette.bg_1, bg = palette.bg_1 },
		PmenuSel = { fg = palette.bg_0, bg = palette.fg_0 },
		PmenuThumb = { bg = palette.fg_2 },
		PreCondit = { fg = palette.fg_1 },
		PreProc = { fg = palette.fg_0 },
		Question = { fg = palette.fg_0 },
		QuickFixLine = { bg = palette.bg_2 },
		Repeat = { fg = palette.indigo },
		Search = { fg = palette.bg_0, bg = palette.fg_2 },
		SignColumn = { bg = palette.bg_0 },
		Special = { fg = palette.fg_0 },
		SpecialChar = { fg = palette.fg_1 },
		SpecialComment = vim.tbl_extend("force", { fg = palette.fg_1 }, opts.styles.comments),
		SpecialKey = { fg = palette.blue },
		SpellBad = { sp = palette.error, undercurl = true },
		SpellCap = { sp = palette.yellow, undercurl = true },
		SpellLocal = { sp = palette.sign_add, undercurl = true },
		SpellRare = { sp = palette.blue, undercurl = true },
		Statement = { fg = palette.indigo },
		StorageClass = { fg = palette.indigo },
		String = { fg = palette.lemongrass },
		Structure = { fg = palette.indigo },
		Substitute = { fg = palette.bg_0, bg = palette.lemongrass },
		TabLine = { fg = palette.fg_2, bg = palette.bg_2 },
		TabLineFill = { fg = palette.fg_0, bg = palette.bg_2 },
		TabLineSel = { fg = palette.fg_0, bg = palette.bg_2 },
		Tag = { fg = palette.indigo },
		TermCursor = { fg = palette.fg_1, bg = palette.bg_0 },
		TermCursorNC = { fg = palette.fg_1, bg = palette.bg_0 },
		Title = { fg = palette.blue },
		Todo = { fg = palette.blue, bg = palette.bg_0, bold = true },
		Type = vim.tbl_extend("force", { fg = palette.violet }, opts.styles.type),
		Typedef = { fg = palette.fg_0 },
		Underlined = { underline = true },
		Variable = vim.tbl_extend("force", { fg = palette.fg_0 }, opts.styles.variables),
		VertSplit = { fg = palette.bg_0, bg = palette.bg_2 },
		Visual = { fg = palette.bg_0, bg = palette.visual },
		VisualNOS = { fg = palette.bg_0, bg = palette.visual },
		WarningMsg = { fg = palette.error, bg = palette.bg_0 },
		Whitespace = { fg = palette.bg_2 },
		WildMenu = { fg = palette.blue, bg = palette.bg_2 },
		WinSeparator = { fg = palette.fg_1, bg = palette.bg_0 },
		lCursor = { fg = palette.fg_1, bg = palette.bg_0 },
		diff_added = { fg = palette.turquoise, bg = palette.diff_added },
		diff_changed = { fg = palette.blue, bg = palette.diff_changed },
		diff_removed = { fg = palette.red, bg = palette.diff_removed },
		-- DiffAdd = { bg = palette.neogit_green },
		-- DiffChange = { fg = palette.sign_change, bg = palette.neogit_blue },
		-- DiffDelete = { fg = palette.sign_delete, bg = palette.neogit_red },
		-- DiffText = { bg = palette.neogit_blue },
	}
end

return M
