local M = {}

function M.highlight(palette, opts)
	return {
		-- diffBDiffer = { fg = palette.fg_0, bg = palette.bg_0 },
		-- diffCommon = { fg = palette.fg_0, bg = palette.bg_0 },
		-- diffDiffer = { fg = palette.fg_0, bg = palette.bg_0 },
		-- diffFile = { fg = palette.fg_0, bg = palette.bg_0 },
		-- diffIdentical = { fg = palette.fg_0, bg = palette.bg_0 },
		-- diffIndexLine = { fg = palette.fg_0, bg = palette.bg_0 },
		-- diffIsA = { fg = palette.fg_0, bg = palette.bg_0 },
		-- diffLine = { fg = palette.fg_0, bg = palette.bg_0 },
		-- diffNewFile = { fg = palette.fg_0, bg = palette.bg_0 },
		-- diffNoEOL = { fg = palette.fg_0, bg = palette.bg_0 },
		-- diffOldFile = { fg = palette.fg_0, bg = palette.bg_0 },
		-- diffOnly = { fg = palette.fg_0, bg = palette.bg_0 },
		-- diffSubname = { fg = palette.fg_0, bg = palette.bg_0 },
		DiffAdd = { fg = palette.turquoise, bg = palette.diff_added },
		DiffChange = { fg = palette.indigo, bg = palette.diff_changed },
		DiffDelete = { fg = palette.red, bg = palette.diff_removed },
		DiffText = { fg = palette.indigo, bg = palette.diff_changed },
		-- :h gitsigns-highlight-groups
		GitSignsAdd = { fg = palette.sign_add },
		GitSignsAddLn = { fg = palette.sign_add, bg = palette.diff_added },
		GitSignsAddCul = { fg = palette.sign_add, bg = palette.bg_2 },
		GitSignsChange = { fg = palette.sign_change },
		GitSignsChangeLn = { fg = palette.sign_change, bg = palette.diff_changed },
		GitSignsChangeCul = { fg = palette.sign_change, bg = palette.bg_2 },
		GitSignsChangedeleteCul = { bg = palette.bg_2 },
		GitSignsDelete = { fg = palette.sign_delete },
		GitSignsDeleteLn = { fg = palette.sign_delete, bg = palette.diff_removed },
		GitSignsDeleteCul = { fg = palette.sign_delete, bg = palette.bg_2 },
		GitSignsTopdeleteCul = { bg = palette.bg_2 },
		GitSignsUntracked = { fg = palette.fg_2 },
		GitSignsUntrackedNr = { fg = palette.fg_2 },
		GitSignsUntrackedLn = { fg = palette.fg_2, bg = palette.bg_2 },
		GitSignsUntrackedCul = { fg = palette.fg_2, bg = palette.bg_2 },
		SignAdd = { fg = palette.sign_add },
		SignChange = { fg = palette.sign_change },
		SignDelete = { fg = palette.sign_delete },
		diffAdded = { fg = palette.turquoise, bg = palette.diff_added },
		diffChanged = { fg = palette.indigo, bg = palette.diff_changed },
		diffComment = { fg = palette.fg_2, bg = palette.bg_0 },
		diffRemoved = { fg = palette.red, bg = palette.diff_removed },
		diff_added = { fg = palette.turquoise, bg = palette.diff_added },
		diff_changed = { fg = palette.indigo, bg = palette.diff_changed },
		diff_removed = { fg = palette.red, bg = palette.diff_removed },
	}
end

return M
