local M = {}

function M.highlight(palette, opts)
	local groups = {
		["@annotation"] = { fg = palette.fg_0 },
		-- ["@attribute.builtin"] = {},
		["@attribute"] = { fg = palette.fg_0 },
		["@boolean"] = { fg = palette.turquoise },
		-- ["@character.special"] = {},
		["@character"] = { fg = palette.turquoise },
		-- ["@comment.error"] = {},
		-- ["@comment.note"] = {},
		["@comment.todo"] = { fg = palette.comment_todo, italic = true },
		["@comment.warning"] = { fg = palette.comment_warning },
		["@comment"] = vim.tbl_extend("force", { fg = palette.fg_2, italic = true }, opts.styles.comments),
		["@conditional"] = { fg = palette.indigo },
		["@const.builtin"] = { fg = palette.red },
		["@const.macro"] = { fg = palette.lemongrass },
		-- ["@constant.builtin"] = {},
		["@constant.falsy"] = { fg = palette.turquoise },
		["@constant"] = { fg = palette.fg_0 },
		["@constructor"] = { fg = palette.fg_0 },
		-- ["@diff.delta"] = {},
		-- ["@diff.minus"] = {},
		-- ["@diff.plus"] = {},
		["@emphasis"] = { italic = true },
		["@error"] = { fg = palette.error },
		["@exception"] = { fg = palette.indigo, italic = true },
		["@field"] = { fg = palette.indigo_hc },
		["@float"] = { fg = palette.gold },
		["@function.builtin"] = { fg = palette.indigo_hc },
		["@function.call"] = { fg = palette.indigo_hc },
		["@function.macro"] = { fg = palette.indigo_hc },
		["@function"] = vim.tbl_extend("force", { fg = palette.indigo_hc }, opts.styles.functions),
		-- ["@ibl.indent.char.1"] = {},
		-- ["@ibl.scope.char.1"] = {},
		-- ["@ibl.scope.underline.1"] = {},
		-- ["@ibl.whitespace.char.1"] = {},
		["@include"] = { fg = palette.indigo },
		["@keyword.coroutine"] = { fg = palette.indigo },
		["@keyword.function"] = vim.tbl_extend("force", { fg = palette.indigo }, opts.styles.keywords),
		["@keyword.operator"] = { fg = palette.indigo },
		["@keyword.return"] = { fg = palette.indigo, italic = true },
		["@keyword"] = vim.tbl_extend("force", { fg = palette.indigo }, opts.styles.keywords),
		["@label"] = { fg = palette.fg_0 },
		["@literal"] = { fg = palette.fg_1 },
		-- ["@lsp.mod.deprecated"] = {},
		-- ["@lsp.type.class"] = {},
		-- ["@lsp.type.comment"] = {},
		-- ["@lsp.type.decorator"] = {},
		-- ["@lsp.type.enum"] = {},
		-- ["@lsp.type.enumMember"] = {},
		-- ["@lsp.type.event"] = {},
		-- ["@lsp.type.function"] = {},
		-- ["@lsp.type.interface"] = {},
		-- ["@lsp.type.keyword"] = {},
		-- ["@lsp.type.macro"] = {},
		-- ["@lsp.type.method"] = {},
		-- ["@lsp.type.modifier"] = {},
		-- ["@lsp.type.namespace"] = {},
		-- ["@lsp.type.number"] = {},
		-- ["@lsp.type.operator"] = {},
		-- ["@lsp.type.parameter"] = {},
		-- ["@lsp.type.property"] = {},
		-- ["@lsp.type.regexp"] = {},
		-- ["@lsp.type.string"] = {},
		-- ["@lsp.type.struct"] = {},
		-- ["@lsp.type.type"] = {},
		-- ["@lsp.type.typeParameter"] = {},
		-- ["@lsp.type.variable"] = {},
		-- ["@markup.heading.1.delimiter.vimdoc"] = {},
		["@markup.heading.1.marker"] = { fg = palette.violet },
		["@markup.heading.1"] = { fg = palette.indigo_hc },
		-- ["@markup.heading.2.delimiter.vimdoc"] = {},
		["@markup.heading.2.marker"] = { fg = palette.violet },
		["@markup.heading.2"] = { fg = palette.indigo_hc },
		["@markup.heading.3.marker"] = { fg = palette.violet },
		["@markup.heading.3"] = { fg = palette.indigo_hc },
		["@markup.heading.4.marker"] = { fg = palette.violet },
		["@markup.heading.4"] = { fg = palette.indigo_hc },
		-- ["@markup.heading"] = {},
		-- ["@markup.italic"] = {},
		-- ["@markup.link"] = {},
		["@markup.list"] = { fg = palette.violet },
		["@markup.raw.delimiter"] = { fg = palette.indigo_hc },
		["@markup.raw"] = { fg = palette.fg_2 },
		-- ["@markup.strikethrough"] = {},
		-- ["@markup.strong"] = {},
		-- ["@markup.underline"] = {},
		-- ["@markup"] = {},
		["@method.call"] = { fg = palette.indigo_hc },
		["@method"] = { fg = palette.indigo_hc },
		-- ["@module.builtin"] = {},
		-- ["@module"] = {},
		["@namespace"] = { fg = palette.violet },
		-- ["@number.float"] = {},
		["@number"] = { fg = palette.gold },
		["@operator"] = { fg = palette.red },
		["@parameter.reference"] = { fg = palette.fg_0 },
		["@parameter"] = { fg = palette.fg_0 },
		["@property.class"] = { fg = palette.blue },
		["@property.id"] = { fg = palette.turquoise },
		["@property"] = { fg = palette.indigo_hc },
		["@punctuation.bracket"] = { fg = palette.indigo },
		["@punctuation.delimiter"] = { fg = palette.indigo },
		["@punctuation.special"] = { fg = palette.indigo },
		-- ["@punctuation"] = {},
		["@query.linter.error"] = { fg = palette.warning },
		["@repeat"] = { fg = palette.indigo },
		["@string.documentation"] = { fg = palette.fg_2 },
		["@string.escape"] = { fg = palette.blue },
		["@string.regex"] = { fg = palette.lemongrass },
		-- ["@string.regexp"] = {},
		["@string.special.url"] = { fg = palette.blue, underline = true },
		-- ["@string.special"] = {},
		["@string"] = { fg = palette.lemongrass },
		["@strong"] = { fg = palette.fg_1 },
		["@structure"] = { fg = palette.fg_1 },
		["@symbol"] = { fg = palette.fg_1 },
		["@tag.attribute"] = { fg = palette.indigo },
		-- ["@tag.builtin"] = {},
		["@tag.delimiter"] = { fg = palette.indigo },
		["@tag"] = { fg = palette.indigo_hc },
		["@text.danger"] = { fg = palette.comment_danger },
		["@text.diff.add"] = { fg = palette.turquoise },
		["@text.diff.delete"] = { fg = palette.red },
		["@text.note"] = { fg = palette.fg_1 },
		["@text.reference"] = { fg = palette.indigo_hc, underline = true },
		["@text.title.1.marker"] = { fg = palette.violet },
		["@text.title.2.marker"] = { fg = palette.violet },
		["@text.title.3.marker"] = { fg = palette.violet },
		["@text.title.4.marker"] = { fg = palette.violet },
		["@text.title"] = { fg = palette.indigo_hc },
		["@text.todo"] = { fg = palette.comment_todo, italic = true },
		["@text.uri"] = { fg = palette.blue, underline = true },
		["@text.warning"] = { fg = palette.comment_warning },
		["@text"] = { fg = palette.fg_0 },
		["@title"] = { fg = palette.blue },
		["@type.builtin"] = { fg = palette.violet },
		["@type"] = vim.tbl_extend("force", { fg = palette.violet }, opts.styles.type),
		["@underline"] = { underline = true },
		["@uri"] = { fg = palette.lemongrass, underline = true },
		["@variable.builtin"] = { fg = palette.fg_0 },
		-- ["@variable.parameter.builtin"] = {},
		["@variable"] = vim.tbl_extend("force", { fg = palette.fg_0 }, opts.styles.variables),
	}

	return groups
end

return M
