local M = {}

function M.highlight(palette, opts)
	return {
		Bold = { bold = true },
		Boolean = { fg = palette.turquoise },
		Character = { fg = palette.green },
		ColorColumn = { bg = palette.accent },
		Comment = vim.tbl_extend("force", { fg = palette.gray }, opts.styles.comments),
		Conceal = { fg = palette.accent },
		Conditional = { fg = palette.indigo },
		Constant = { fg = palette.white },
		Cursor = { fg = palette.light_gray, bg = palette.alt_bg },
		CursorColumn = { bg = palette.accent },
		CursorIM = { fg = palette.light_gray, bg = palette.alt_bg },
		CursorLine = { bg = palette.accent },
		CursorLineNr = { fg = palette.light_gray, bold = true },
		Debug = { fg = palette.blue },
		Define = { fg = palette.blue },
		Delimiter = { fg = palette.indigo },
		DiagnosticFloatingError = { fg = palette.error },
		Directory = { fg = palette.blue },
		EndOfBuffer = { fg = palette.alt_bg },
		Error = { fg = palette.error, bold = true },
		ErrorMsg = { fg = palette.error, bold = true },
		Exception = { fg = palette.blue },
		Float = { fg = palette.gold },
		FloatBoder = { fg = palette.gray, bg = palette.accent },
		FloatBorder = { fg = palette.light_gray },
		FoldColumn = { fg = palette.light_gray, bg = palette.accent },
		Folded = { fg = palette.light_gray, bg = palette.accent },
		Function = vim.tbl_extend("force", { fg = palette.white }, opts.styles.functions),
		Identifier = { fg = palette.white },
		Ignore = { fg = palette.white, bg = palette.alt_bg, bold = true },
		IncSearch = { fg = palette.accent, bg = palette.lemongrass },
		Include = { fg = palette.medium_gray },
		Italic = { italic = true },
		Keyword = vim.tbl_extend("force", { fg = palette.indigo }, opts.styles.keywords),
		Label = { fg = palette.white },
		LineNr = { fg = palette.gray },
		Macro = { fg = palette.white },
		MatchParen = { fg = palette.light_gray, bg = palette.none },
		MatchParenCur = { underline = true },
		MatchWord = { underline = true },
		MatchWordCur = { underline = true },
		ModeMsg = { fg = palette.fg, bg = palette.alt_bg },
		MoreMsg = { fg = palette.white },
		MsgArea = { fg = palette.fg, bg = palette.alt_bg },
		MsgSeparator = { fg = palette.fg, bg = palette.alt_bg },
		NonText = { fg = palette.alt_bg },
		Normal = { fg = palette.fg, bg = opts.transparent and palette.none or palette.alt_bg },
		NormalFloat = { bg = palette.accent },
		NormalNC = { fg = palette.fg, bg = palette.alt_bg },
		Number = { fg = palette.gold },
		Operator = { fg = palette.pink },
		Pmenu = { fg = palette.light_gray, bg = palette.accent },
		PmenuSbar = { bg = palette.accent },
		PmenuSel = { fg = palette.accent, bg = palette.gold },
		PmenuThumb = { bg = palette.light_gray },
		PreCondit = { fg = palette.medium_gray },
		PreProc = { fg = palette.white },
		Question = { fg = palette.white },
		QuickFixLine = { bg = palette.accent },
		Repeat = { fg = palette.indigo },
		Search = { fg = palette.alt_bg, bg = palette.medium_gray },
		SignColumn = { bg = palette.alt_bg },
		Special = { fg = palette.white },
		SpecialChar = { fg = palette.medium_gray },
		SpecialComment = vim.tbl_extend("force", { fg = palette.gray }, opts.styles.comments),
		SpecialKey = { fg = palette.blue },
		SpellBad = { sp = palette.error, undercurl = true },
		SpellCap = { sp = palette.yellow, undercurl = true },
		SpellLocal = { sp = palette.sign_add, undercurl = true },
		SpellRare = { sp = palette.purple, undercurl = true },
		Statement = { fg = palette.indigo },
		StorageClass = { fg = palette.indigo },
		String = { fg = palette.lemongrass },
		Structure = { fg = palette.indigo },
		Substitute = { fg = palette.alt_bg, bg = palette.lemongrass },
		TabLine = { fg = palette.gray, bg = palette.accent },
		TabLineFill = { fg = palette.white, bg = palette.accent },
		TabLineSel = { fg = palette.white, bg = palette.accent },
		Tag = { fg = palette.indigo },
		TermCursor = { fg = palette.light_gray, bg = palette.alt_bg },
		TermCursorNC = { fg = palette.light_gray, bg = palette.alt_bg },
		Title = { fg = palette.blue },
		Todo = { fg = palette.blue, bg = palette.alt_bg, bold = true },
		Type = vim.tbl_extend("force", { fg = palette.violet }, opts.styles.type),
		Typedef = { fg = palette.white },
		Underlined = { underline = true },
		Variable = vim.tbl_extend("force", { fg = palette.white }, opts.styles.variables),
		VertSplit = { fg = palette.alt_bg, bg = palette.accent },
		Visual = { bg = palette.gray },
		VisualNOS = { bg = palette.accent },
		WarningMsg = { fg = palette.error, bg = palette.alt_bg },
		Whitespace = { fg = palette.gray },
		WildMenu = { fg = palette.blue, bg = palette.accent },
		WinSeparator = { fg = palette.medium_gray, bg = palette.alt_bg },
		lCursor = { fg = palette.light_gray, bg = palette.alt_bg },
		-- DiffAdd = { bg = palette.neogit_green },
		-- DiffChange = { fg = palette.sign_change, bg = palette.neogit_blue },
		-- DiffDelete = { fg = palette.sign_delete, bg = palette.neogit_red },
		-- DiffText = { bg = palette.neogit_blue },
	}
end

return M
